### ISSUE TITLE
Spectrum office hours social media image

### ISSUE THREAD

**Issue by broccolini** [primer/primer.style#103]
We see a lot more engagement on twitter when we have nice visuals or gifs, wondering if it's worth making something that will stand out a little more for our office hours chat this Friday? cc @ashygee

**Comment by ashygee** [comment]
@broccolini yes! I think that's a great idea. Let me whip something up

**Comment by ashygee** [comment]
@broccolini I've mocked up these two with the Primer paintbrush. I wasn't sure if you wanted the images to actually read "Primer office hours" or more like the Valentine's day images just be an illustration. Both are in the [Social Posts](https://www.figma.com/file/GKpAOgd1ZtMc79uLyzWj1KE6/Social-Posts?node-id=0%3A1) figma file.

### Option 1
![office-hours](https://user-images.githubusercontent.com/10384315/53213194-caaee100-35fc-11e9-8596-a5a03c943a9f.jpg)

### Option 2
![office-hours-2](https://user-images.githubusercontent.com/10384315/53213196-cc78a480-35fc-11e9-9a46-89f2e8bea513.jpg)

**Comment by ashygee** [comment]
Edit notes:

- Add copy "Office house on Spectrum!"
- Update image to highlight Spectrum more.

**Comment by broccolini** [comment]
I don't think we have a need for this anymore, and better to create custom social media images as needed. Closing.
