### ISSUE TITLE
Add google analytics

### ISSUE THREAD

**Issue by broccolini** [primer/primer.style#13]
cc @jonrohan

**Comment by jonrohan** [comment]
I went to make one on our github account and we're maxed out on properties right now 😫 

![image](https://user-images.githubusercontent.com/54012/45862179-6a520580-bd25-11e8-9faa-b09716ce847f.png)

**Comment by broccolini** [comment]
@jonrohan omg lol! Any idea who owns this account? I guess the Gear folks might manage this?
