### ISSUE TITLE
Problems loading the site on Firefox

### ISSUE THREAD

**Issue by gimenete** [primer/primer.style#141]
👋 

I found issues loading the examples on Firefox:

Sometimes they don't load at all
<img width="972" alt="Screen Shot 2019-06-05 at 14 43 08" src="https://user-images.githubusercontent.com/50486/58957257-8b1d9680-87a0-11e9-81f6-f1ca1f642ee9.png">

Sometimes I see only part of the content
<img width="956" alt="Screen Shot 2019-06-05 at 14 44 53" src="https://user-images.githubusercontent.com/50486/58957260-8ce75a00-87a0-11e9-9131-8fcc74794e1d.png">

Looks like there are some iframes that sometimes have a height of 0px and sometimes the have some height but not enough to show the content.

**Comment by yaili** [comment]
I can't replicate this issue. Please reopen if still needed. Thank you!
