### ISSUE TITLE
Add Presentations to Design dropdown in main nav

### ISSUE THREAD

**Issue by ashygee** [primer/primer.style#150]
<img width="236" alt="Screenshot 2019-06-25 16 30 18" src="https://user-images.githubusercontent.com/10384315/60140399-8710e300-9766-11e9-9736-78e5665a1137.png">

We need to add Presentations here so that it is more easily accessible.

**Comment by yaili** [comment]
I believe this is done. Closing.

<img width="403" alt="Screenshot 2020-01-24 at 16 59 43" src="https://user-images.githubusercontent.com/223966/73087801-f8666f00-3eca-11ea-8779-7dc8bc7c9ddb.png">
