### ISSUE TITLE
Primer.style hompepage update: Release 4

### ISSUE THREAD

**Issue by broccolini** [primer/primer.style#155]
See https://github.com/primer/primer.style/issues/135

- [ ] Add new Open Source section

<img width="360px" src="https://user-images.githubusercontent.com/334891/60400482-37edf800-9b42-11e9-853a-4c9503af3660.png">

**Comment by yaili** [comment]
Closing and adding as a reference for #135

**Comment by yaili** [comment]
Closing and adding as a reference for #135
