### ISSUE TITLE
Octicons-v2 webpage not found

### ISSUE THREAD

**Issue by misode** [primer/primer.style#198]
https://primer.style/octicons-v2/
![image](https://user-images.githubusercontent.com/17352009/84327917-e2f39800-ab80-11ea-8464-b0d65b456a5c.png)

**Comment by yaili** [comment]
Hi @misode 

Can you tell me where you found that link, so we can correct it?

Thank you

**Comment by misode** [comment]
I had it bookmarked, but the link was also on https://primer.style/octicons. The link seems to have been removed in https://github.com/primer/octicons/commit/4feef6b26197a42d3aebb1767f012df46e80e434 shortly after I made this issue.

**Comment by yaili** [comment]
@misode this should be working now, with the right redirect. Thanks again for flagging!

**Comment by misode** [comment]
It is indeed working, thanks for the quick fix!
