### ISSUE TITLE
Design and Development navbar dropdowns are broken on https://primer.style/components

### ISSUE THREAD

**Issue by scotttesler** [primer/primer.style#242]
The `Design` and `Development` dropdown buttons in the navbar are broken on the `https://primer.style/components(/*)` page(s). I have tested this on Chrome, Brave, and Safari.

https://user-images.githubusercontent.com/586779/119149535-9ca6ea00-ba1b-11eb-8a6c-e319162a306c.mov

**Comment by yaili** [comment]
Thank you @scotttesler - I will leave this issue open here so that folks know that we're tracking this bug in the Primer React Components repo -> https://github.com/primer/components/issues/1073 🙂

**Comment by colebemis** [comment]
Fixed ✅
