### ISSUE TITLE
ACTION REQUIRED: GLB TLS Certificate expiration for primer.style

### ISSUE THREAD

**Issue by octocerts** [primer/primer.style#406]
# ACTION REQUIRED - Certificate Expiration for primer.style on 2024-11-07

Hello! :wave:

The GLB TLS certificate for primer.style expires on 2024-11-07.
Expiring certificate serial: 0404f9e2ecca26e5d3bb88c967d26de76695

The new certificate has been placed in Vault:

Application: primer-style
Environment: production

Key for GLB Certificate + Private Key: TLS_CERTIFICATE

Deploying the application will automatically update the certificate. Please close this issue when you have verified the renewal of your certificate.

If you believe that your team has received this issue in error, please reach out to us in [#secure-access-engineering](https://github.slack.com/archives/C028X7VQ74J) in Slack.

**Comment by lesliecdubs** [comment]
Sending this into the Primer FR queue. FR: if you don't know how to execute on this issue, feel free to reach out to the Slack channel listed in the summary, or @camertron might be able to provide some support.

**Comment by camertron** [comment]
Hey there 👋 We don't actually use this cert, so we can safely disregard this issue. I've filed two PRs that should prevent them in the future:

1. https://github.com/github/octocerts-config/pull/806
2. https://github.com/github/secrets-federation/pull/1453

**Comment by francinelucca** [comment]
Closing as this looks to have been resolved
