### ISSUE TITLE
Decide on what the Meet the Team questions are - @broccolini

### ISSUE THREAD

**Issue by broccolini** [primer/primer.style#42]
Here's the team questions/outline:

- Name, Title
- GitHub handle
- Favorite CSS feature
- What drew you to design systems?
- Who have you learned from or been inspired by?
- Favorite tools

**Comment by broccolini** [comment]
Here is an example:

**Diana Mounter, Design Operations Manager**

GitHub handle: @broccolini

**Favorite CSS feature:** text-decoration: underline wavy

**What drew you to design systems?**
I was drawn to design systems for many reasons—the opportunity to improve design and development workflow efficiency; the potential benefits well-design systems can bring to the user experience; I like to bring order to chaos and enjoy working at the intersection of design and code. I also love that there is still so much to learn in the field and really enjoy the passion of the community behind design systems.

**Who have you learned from or been inspired by?**
I don't have room on this webpage to list everyone! [SMACSS](https://smacss.com/), [The Art and Science of CSS](https://www.amazon.com/Science-Jonathan-Bolton-Cameron-Paperback/dp/B00ZVORUW6), and [Veerle Pieters](http://veerle.duoh.com/) were some early influences. OOCSS by Nicole Sullivan, CSS Wizardary, Basscss, Tachyons, and BEM influenced my approach to CSS architecture. More recently I've been inspired by Rune Madsen's Programming Design Systems, Compositor, Dan Abramov, Sebastian Markbage, and so many design and code wonder women like Many Kerr, Marcy Sutton, Lea Verou, Sarah Drasner and Jina Anne.

**Favorite tools:** Hyper, Atom, Figma, MDN, and Quip

**Comment by broccolini** [comment]
@emilybrick @emplums One thing I noticed is that we probably want to hyperlink a lot of the things in "what have you learned from or been inspired by?" so should make sure that looks good.

**Comment by emplums** [comment]
@primer/design-systems feel free to return your answers in JSON format to get a gold star ⭐️ 
```
{
 name: 'Emily Plummer',
 title: 'Design Systems Engineer',
 handle: 'emplums',
 cssFeature: 'word-break: break-word'
 questionOne: '',
 questionTwo: '',
 favoriteTools: ''
}
```

**Comment by jonrohan** [comment]
```
{
    name: 'Jon Rohan',
    handle: 'Systems Designer',
    github: 'jonrohan',
    cssFeature: `grid-template-areas: "header header header" "footer footer footer"`,
    questionOne: `I have had a facination with front end engineering and UI for all of my career. Early on at GitHub I recognized the need to organize our code into reusable components. When the team formalized I had to be involed.`,
    questionTwo: `Both past and present I have to acknowledge that Nicole Sullivan has been profoundly influential in the way I front-end and write CSS. When she introduced concepts of OOCSS it brought me from thinking very linearly about CSS to a whole new range of systems thinking.`,
    favoriteTools: `Atom, Bash/Shell, Figma, GitHub, iTerm, Javascript, MacBook Pro, Things`,
    avatar: 'https://user-images.githubusercontent.com/8960591/46552728-6dee9c00-c890-11e8-827f-89fa8a58441d.jpg'
  }
```

**Comment by emilybrick** [comment]
``` JS
{
    name: 'Emily Brick',
    title: 'Systems Designer',
    handle: 'emilybrick',
    cssFeature: 'align-items: center;',
    questionOne: `I was initially drawn to design systems while working on a small team, where we were stretched thin and struggling to keep the front-end and user experience afloat, recreating components and patterns by hand over and over again. We needed consistency, stability, a bridge between designers and developers, and a more efficient workflow. Once we put a design language and system in place, I was sold on the value. I find it fascinating how many approaches to design systems there are out there, and how different they can be depending on the individual product and teams’ needs.`,
    questionTwo: `[Inge Druckrey](https://www.youtube.com/watch?v=ldSkPqZKBl0) and [Edward Tufte](https://www.edwardtufte.com/tufte/books_ei) inspired me to get into design, and introduced me to the world of typographic and informational systems (simultaneously). This talk by [Bret Victor](https://vimeo.com/36579366) helped me feel less alone when I was starting out in the industry; at a time when code and design weren't yet openly intertwined. I’m also inspired by the folks behind designbetter.co for making knowledge around design systems transparent and available to everyone.  Additionally, and there are too many people to name, people like Una Kravetz, Sarah Drasner, Tim Holman, and Val Head are always on my radar, keeping the internet weird and creative and continuously pushing the boundaries of what's possible.`,
    favoriteTools: 'Atom, Figma, Bear, Dash, Slack',
  }
```

**Comment by broccolini** [comment]
Shipped 🚀 https://primer.style/team
