### ISSUE TITLE
OG Images for Twitter, FB, and Slack

### ISSUE THREAD

**Issue by emilybrick** [primer/primer.style#74]
[(original PR for reference) ](https://github.com/primer/components/pull/324)

After doing a bit of research, I think we should create an OG image that works for all three platforms rather than try to style Facebook's preview differently. 

As per the [developer documentation](https://developers.facebook.com/docs/sharing/best-practices/#images), **1200 by 630** is the recommended size. You can, however, set separate images for Twitter and Facebook [(as Atom is doing now, documented a bit here)](https://docs.google.com/document/d/1up4SCajKWHxT5JdTBHRZZ4LKNF21-BJd9Pr4FsgZaPU/edit?usp=sharing) but they're still the same size (both 1200 by 630). 

Because we have a square OG image, It looks like even on Twitter our OG images are getting cropped:
![screenshot 2018-10-25 11 51 23](https://user-images.githubusercontent.com/586552/47513617-a0b30100-d84c-11e8-812a-9e29b21e1e0c.png)

which we could solve by fixing that aspect ratio to the recommended dimensions.

Though the square aspect ratio works for Slack, I think we can adjust the composition to work well in a 1200 x 630 frame. Let me know your thoughts and I can drop a few iterations in here at that size (for both primer.style & /components)

**Comment by emplums** [comment]
I agree this seems like the right way to go about it!

**Comment by ashygee** [comment]
Closing this issue and continuing conversation in #85.
