### ISSUE TITLE
README Image concepts

### ISSUE THREAD

**Issue by ashygee** [primer/primer.style#90]
Per the conversation with @broccolini on Primer illustrations, I've updated the readme concepts for the primer/styles and primer/components readme's.

![screenshot 2018-11-20 16 15 32](https://user-images.githubusercontent.com/10384315/48810721-84857100-ecdf-11e8-8b2f-4ea87235198d.png)

You can view in detail in the figma file. I've also included some mocks of what the readme will look like when viewed on GitHub.  [View in Figma](https://www.figma.com/file/Gjh5FeUtWhNWXf3ksZoWxeFM/Exploration-v1?node-id=5%3A1)

**Comment by ashygee** [comment]
<img width="550" alt="screenshot 2018-11-21 12 05 03" src="https://user-images.githubusercontent.com/10384315/48865868-b7824000-ed85-11e8-9b2a-34888a0fa065.png">

Trying to get closer to the website illustration styles. I took some of the inspiration from this image:
<img width="404" alt="screenshot 2018-11-21 12 05 28" src="https://user-images.githubusercontent.com/10384315/48865875-c0731180-ed85-11e8-85f9-2a29e7be4e6f.png">

* Reverted the Octicon's to their original positioning
* Playing with the stroke widths. I'm now using the same stroke widths of .75pt and 2pt as seen in the website illustration files
* Removed overlapping of outlined geometric shapes

**Comment by broccolini** [comment]
Thanks @ashygee this is heading in the right direction! Some feedback below:

- The far left options look best to me, though I'd be interested in seeing an option with light blue dots outside the box similar to how they do it on the site pages.
- I think these should be a test case for the updated/consolidated styles so I'd like to see the single color thin lines vs thicker stroke lighter blue lines (like the site illos)
- The hand-drawn style line connects the octicons in other illustrations we have, so the line appears to come out of the end of the icon, on these ones it seems to be connecting the boxes instead which doesn't feel right to me - let me know if there is a reason for this though
- Outline shapes like the hexagon and the circle shouldn't overlap. From what I've seen on the site designs they do not overlap. We shouldn't do that either. (I noticed we do on the team page illo so we should fix that.)
- The lightning bolt icon rotated looks odd. I don't think any octicons should be rotated.
- The top right option has a the top line of code blocks very close to the edge, when we use the code blocks I think they should obviously overlap the edge of a shape or have a good amount of space.

**Comment by ashygee** [comment]
@broccolini I've gone ahead and fine-tuned the concepts with your feedback. The concepts for primer/styles and primer/components both have three different variations for background:

* A: Outline Box
* B: Dot Pattern
* C: Outline Box + Dot Pattern

### primer/styles concepts
![screenshot 2018-11-27 15 07 36](https://user-images.githubusercontent.com/10384315/49117626-31b73680-f256-11e8-8d17-e40dcafcdaa1.png)

### primer/components concepts
![screenshot 2018-11-27 14 56 56](https://user-images.githubusercontent.com/10384315/49117172-b6a15080-f254-11e8-9ed7-0ca8308fca30.png)

### Details
* For **Style A** I wanted to focus on the simplicity of Primer's style. For both /style and /components I've used the primitive shapes seen in the original primer banners. 
* The dot pattern for **B** & **C** has been lightened to blue-100 in order to better suit the white background of the readme on github.com and npm.
* The dot pattern on **C** is thinner to take into account of the outline box pairing.
* Stroke width variation is now similar to the web illustrations. 1px stroke is used for all connecting lines. The thicker stroke is consistent at 2px.
* 3px stroke for the squiggle paired with the paintbrush and the outline on style **B**.
* For the /components concepts the hand-drawn line connects the octicons as seen in the other illustrations instead of the blocks.
* Octicons have been rotated/flipped back to their correct and original positioning.
* Each overlapping element maintains consistent spacing with our spacing guidelines by being on a base 8.
![screenshot 2018-11-27 14 54 00](https://user-images.githubusercontent.com/10384315/49117091-7b068680-f254-11e8-99c6-637fd3b8036a.png)

### Mocks
Example screen mocks of the README images can be seen in full resolution in [Figma](https://www.figma.com/file/Gjh5FeUtWhNWXf3ksZoWxeFM/Exploration-v1?node-id=82%3A513).

![screenshot 2018-11-27 15 12 55](https://user-images.githubusercontent.com/10384315/49117883-1f89c800-f257-11e8-843a-f849b86e9ffc.png)
![screenshot 2018-11-27 15 13 07](https://user-images.githubusercontent.com/10384315/49117888-21ec2200-f257-11e8-86dc-edd4dd5c6f65.png)

**Comment by ashygee** [comment]
<img width="1105" alt="screenshot 2018-12-03 14 09 55" src="https://user-images.githubusercontent.com/10384315/49613043-55b3ff80-f95b-11e8-84f4-267db1f03e28.png">

README images live on primer/components and primer/primer.style repos
